"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import { useEffect, useState } from "react";
import Link from "next/link";

const blank = { name: "", email: "", phone: "", line1: "", line2: "", city: "", state: "", pincode: "", country: "PK", dateOfBirth: "" };

export default function ProfilePage() {
  const [form, setForm] = useState(blank); const [customer, setCustomer] = useState<any>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  async function load() { const data = await fetch("/api/customer/profile", { cache: "no-store" }).then((r) => r.json()); setCustomer(data.customer); if (data.customer) setForm({ name: data.customer.name || "", email: data.customer.email || "", phone: data.customer.phone || "", line1: data.customer.address?.line1 || "", line2: data.customer.address?.line2 || "", city: data.customer.address?.city || "", state: data.customer.address?.state || "", pincode: data.customer.address?.pincode || "", country: data.customer.address?.country || "PK", dateOfBirth: data.customer.dateOfBirth?.slice(0, 10) || "" }); setLoading(false); }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const response = await fetch("/api/customer/profile", { method: customer ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.name, email: form.email, phone: form.phone, dateOfBirth: form.dateOfBirth || null, address: { line1: form.line1, line2: form.line2, city: form.city, state: form.state, pincode: form.pincode, country: form.country } }) }); const data = await response.json(); if (response.ok) { setCustomer(data.customer); setMessage("Profile saved successfully."); window.dispatchEvent(new Event("aurevia-profile-saved")); } else setMessage(data.error || "Could not save profile."); setSaving(false); }
  if (loading) return <main className="min-h-[60vh] p-10 text-center">Loading your profile...</main>;
  const fields = [["name","Name"],["email","Email"],["phone","Phone number"],["dateOfBirth","Date of birth"],["line1","Address line 1"],["line2","Address line 2"],["city","City"],["state","State / province"],["pincode","Postal code"]] as const;
  return <main className="min-h-screen bg-[#fcf5e8] px-4 py-10 sm:px-6"><div className="mx-auto max-w-6xl"><h1 className="font-serif text-3xl font-bold">Customer profile</h1><p className="mt-1 text-sm text-[#5A5E55]">Shopping never requires an account. Save these details for this browser and connect your orders and wishlist.</p><div className="mt-7 grid gap-6 lg:grid-cols-[1fr_1.2fr]">
    <form onSubmit={submit} className="rounded-2xl border border-[#C6A24A]/20 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">{customer ? "Edit your details" : "Create your profile"}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{fields.map(([key,label]) => <label key={key} className={key === "line1" || key === "line2" ? "sm:col-span-2 text-sm font-semibold" : "text-sm font-semibold"}>{label}<input required={["name","email","phone","line1","city"].includes(key)} type={key === "email" ? "email" : key === "dateOfBirth" ? "date" : "text"} value={form[key]} onChange={(e) => setForm((f) => ({ ...f, [key]: e.target.value }))} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal outline-none focus:border-[#f6a45d]"/></label>)}</div>{message ? <p className={`mt-4 text-sm font-semibold ${message.includes("success") ? "text-green-700" : "text-red-600"}`}>{message}</p> : null}<button disabled={saving} className="mt-5 rounded-lg bg-[#f6a45d] px-5 py-2.5 font-bold text-white disabled:opacity-50">{saving ? "Saving..." : "Save profile"}</button></form>
    <section className="space-y-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Orders",customer?.stats?.totalOrders || 0],["Completed",customer?.stats?.completedOrders || 0],["Pending",customer?.stats?.pendingOrders || 0],["Spent",`Rs. ${(customer?.stats?.totalSpent || 0).toLocaleString("en-PK")}`]].map(([label,value]) => <div key={label} className="rounded-xl border border-[#C6A24A]/20 bg-white p-4"><p className="text-xs uppercase text-[#5A5E55]">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>)}</div><div className="rounded-2xl border border-[#C6A24A]/20 bg-white p-5"><div className="flex justify-between"><h2 className="text-lg font-bold">Order history</h2><Link href="/wishlist" className="text-sm font-bold text-[#c86f2d]">View wishlist</Link></div>{!customer?.orders?.length ? <p className="mt-4 text-sm text-[#5A5E55]">Your orders will appear here after checkout.</p> : <div className="mt-3 divide-y">{customer.orders.map((order:any) => <div key={order.id} className="flex items-center justify-between gap-4 py-3"><div><p className="font-bold">{order.orderNumber}</p><p className="text-xs text-[#5A5E55]">{new Date(order.createdAt).toLocaleDateString()} · {order.orderStatus}</p></div><p className="font-semibold">Rs. {order.total.toLocaleString("en-PK")}</p></div>)}</div>}</div></section>
  </div></div></main>;
}
