import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/admin-auth";

const schema = z.object({ name: z.string().min(2), email: z.string().email().nullable().optional(), phone: z.string().nullable().optional(), address: z.any().optional(), notes: z.string().nullable().optional() });
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { try { await requireAdmin(); const { id } = await params; const customer = await prisma.customer.findUnique({ where: { id }, include: { orders: { orderBy: { createdAt: "desc" } }, wishlistItems: { include: { product: true }, orderBy: { createdAt: "desc" } }, activities: { orderBy: { createdAt: "desc" }, take: 200 } } }); if (!customer) return NextResponse.json({ error: "Customer not found" }, { status: 404 }); return NextResponse.json({ customer: { ...customer, accessTokenHash: undefined } }); } catch (error) { return NextResponse.json({ error: (error as Error).message }, { status: 401 }); } }
export async function PUT(request: Request, { params }: { params: Promise<{ id: string }> }) { try { await requireAdmin(); const { id } = await params; const input = schema.parse(await request.json()); const customer = await prisma.customer.update({ where: { id }, data: { ...input, email: input.email?.toLowerCase() || null, activities: { create: { type: "admin_updated", description: "Customer record updated by administrator" } } } }); return NextResponse.json({ customer }); } catch (error) { return NextResponse.json({ error: (error as Error).message }, { status: 400 }); } }
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { try { await requireAdmin(); const { id } = await params; await prisma.customer.delete({ where: { id } }); return NextResponse.json({ ok: true }); } catch (error) { return NextResponse.json({ error: (error as Error).message }, { status: 400 }); } }
