"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";

const blank = { name: "", email: "", phone: "", notes: "" };
export default function CustomersPage() {
  const [customers,setCustomers]=useState<any[]>([]); const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [loading,setLoading]=useState(true); const [showCreate,setShowCreate]=useState(false); const [form,setForm]=useState(blank); const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true); const params=new URLSearchParams(); if(search)params.set("search",search); if(status)params.set("status",status); const data=await fetch(`/api/admin/customers?${params}`,{cache:"no-store"}).then(r=>r.json()); setCustomers(data.customers||[]); setLoading(false);},[search,status]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load]);
  async function create(event:React.FormEvent){event.preventDefault();setError("");const response=await fetch("/api/admin/customers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await response.json();if(!response.ok)return setError(data.error||"Could not create customer");setForm(blank);setShowCreate(false);void load()}
  return <div className="p-4 md:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Customer Management</h1><p className="text-sm text-gray-500">Profiles, orders, wishlists, carts and activity records.</p></div><button onClick={()=>setShowCreate(v=>!v)} className="rounded-lg bg-[#1a1308] px-4 py-2 text-sm font-bold text-white">{showCreate?"Cancel":"Create customer"}</button></div>
  {showCreate?<form onSubmit={create} className="mt-5 grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-2 lg:grid-cols-4"><input required placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="rounded-lg border px-3 py-2"/><input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="rounded-lg border px-3 py-2"/><input placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="rounded-lg border px-3 py-2"/><input placeholder="Internal notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="rounded-lg border px-3 py-2"/>{error?<p className="text-sm text-red-600 sm:col-span-2">{error}</p>:null}<button className="rounded-lg bg-[#C6A24A] px-4 py-2 font-bold text-white">Save customer</button></form>:null}
  <div className="my-5 grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-2"><label className="text-xs font-semibold">Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, email or phone" className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label><label className="text-xs font-semibold">Order status<select value={status} onChange={e=>setStatus(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"><option value="">All customers</option>{["pending","confirmed","processing","shipped","completed","cancelled"].map(s=><option key={s}>{s}</option>)}</select></label></div>
  {loading?<p>Loading customers...</p>:!customers.length?<p className="text-gray-500">No matching customers.</p>:<div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{["Customer","Contact","Orders","Completed / Pending","Spent","Wishlist","Created / Active",""].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{customers.map(c=><tr key={c.id}><td className="px-4 py-3 font-bold">{c.name}</td><td className="px-4 py-3"><div>{c.email||"—"}</div><div className="text-gray-500">{c.phone||"—"}</div></td><td className="px-4 py-3">{c.stats.totalOrders}</td><td className="px-4 py-3">{c.stats.completed} / {c.stats.pending}</td><td className="px-4 py-3">Rs. {c.stats.spent.toLocaleString("en-PK")}</td><td className="px-4 py-3">{c._count.wishlistItems}</td><td className="px-4 py-3 text-xs"><div>{new Date(c.createdAt).toLocaleDateString()}</div><div className="text-gray-500">{new Date(c.lastActiveAt).toLocaleString()}</div></td><td className="px-4 py-3"><Link href={`/admin/customers/${c.id}`} className="font-bold text-[#9a6911]">View</Link></td></tr>)}</tbody></table></div>}
  </div>;
}
