"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */

import { useEffect,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import Link from "next/link";

export default function CustomerDetailPage(){const {id}=useParams<{id:string}>();const router=useRouter();const [customer,setCustomer]=useState<any>(null);const [form,setForm]=useState<any>(null);const [error,setError]=useState("");const [saving,setSaving]=useState(false);
  async function load(){const response=await fetch(`/api/admin/customers/${id}`,{cache:"no-store"});const data=await response.json();if(response.ok){setCustomer(data.customer);setForm({name:data.customer.name,email:data.customer.email||"",phone:data.customer.phone||"",notes:data.customer.notes||"",address:data.customer.address||{}})}else setError(data.error)}useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[id]);
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);const response=await fetch(`/api/admin/customers/${id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,email:form.email||null})});const data=await response.json();setSaving(false);if(!response.ok)setError(data.error);else void load()}
  async function remove(){if(!confirm("Delete this customer profile? Orders will be retained without the customer link."))return;const response=await fetch(`/api/admin/customers/${id}`,{method:"DELETE"});if(response.ok)router.push("/admin/customers");else setError("Could not delete customer")}
  if(error&&!customer)return <div className="p-8 text-red-600">{error}</div>;if(!customer||!form)return <div className="p-8">Loading customer...</div>;const completed=customer.orders.filter((o:any)=>o.orderStatus==="completed");const pending=customer.orders.filter((o:any)=>!["completed","cancelled"].includes(o.orderStatus));const cancelled=customer.orders.filter((o:any)=>o.orderStatus==="cancelled");
  return <div className="p-4 md:p-8"><Link href="/admin/customers" className="text-sm font-bold text-[#9a6911]">← All customers</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">{customer.name}</h1><p className="text-sm text-gray-500">Created {new Date(customer.createdAt).toLocaleString()} · Last active {new Date(customer.lastActiveAt).toLocaleString()}</p></div><button onClick={remove} className="rounded-lg border border-red-300 px-4 py-2 text-sm font-bold text-red-600">Delete customer</button></div>{error?<p className="mt-3 text-red-600">{error}</p>:null}
  <div className="mt-6 grid gap-6 xl:grid-cols-[380px_1fr]"><form onSubmit={save} className="rounded-xl border bg-white p-5"><h2 className="font-bold">Customer information</h2><div className="mt-4 space-y-3">{[["name","Name"],["email","Email"],["phone","Phone"]].map(([key,label])=><label key={key} className="block text-xs font-semibold">{label}<input required={key==="name"} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label>)}{[["line1","Address"],["line2","Address line 2"],["city","City"],["state","State"],["pincode","Postal code"],["country","Country"]].map(([key,label])=><label key={key} className="block text-xs font-semibold">{label}<input value={form.address?.[key]||""} onChange={e=>setForm({...form,address:{...form.address,[key]:e.target.value}})} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label>)}<label className="block text-xs font-semibold">Admin notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label></div><button disabled={saving} className="mt-4 rounded-lg bg-[#1a1308] px-4 py-2 text-sm font-bold text-white">{saving?"Saving...":"Save changes"}</button></form>
  <div className="space-y-6"><section className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["All orders",customer.orders.length],["Completed",completed.length],["Pending",pending.length],["Cancelled",cancelled.length]].map(([l,v])=><div key={l} className="rounded-xl border bg-white p-4"><p className="text-xs uppercase text-gray-500">{l}</p><p className="text-2xl font-bold">{v}</p></div>)}</section><Panel title="Orders">{customer.orders.length?<Table rows={customer.orders.map((o:any)=>[<Link key={o.id} className="font-bold text-[#9a6911]" href={`/admin/orders/${o.id}`}>{o.orderNumber}</Link>,o.orderStatus,o.paymentStatus,`Rs. ${o.total.toLocaleString("en-PK")}`,new Date(o.createdAt).toLocaleDateString()])} headings={["Order","Status","Payment","Total","Date"]}/>:<Empty/>}</Panel><Panel title={`Wishlist (${customer.wishlistItems.length})`}>{customer.wishlistItems.length?<Table rows={customer.wishlistItems.map((w:any)=>[w.product.title,`Rs. ${w.product.price.toLocaleString("en-PK")}`,new Date(w.createdAt).toLocaleDateString()])} headings={["Product","Price","Added"]}/>:<Empty/>}</Panel><Panel title={`Activity (${customer.activities.length})`}><div className="divide-y">{customer.activities.map((a:any)=><div key={a.id} className="py-3"><p className="font-semibold">{a.description}</p><p className="text-xs text-gray-500">{a.type} · {new Date(a.createdAt).toLocaleString()}</p></div>)}</div></Panel><Panel title="Last cart snapshot"><pre className="max-h-60 overflow-auto rounded-lg bg-gray-50 p-3 text-xs">{JSON.stringify(customer.cartSnapshot,null,2)}</pre></Panel></div></div></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border bg-white p-5"><h2 className="mb-3 font-bold">{title}</h2>{children}</section>}function Empty(){return <p className="text-sm text-gray-500">No records.</p>}function Table({headings,rows}:{headings:string[];rows:React.ReactNode[][]}){return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{headings.map(h=><th key={h} className="border-b py-2 pr-4 text-xs uppercase text-gray-500">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} className="border-b py-2 pr-4">{c}</td>)}</tr>)}</tbody></table></div>}
